//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Halkidiki.Dal.Interfaces
{
    using System;
    using System.Collections.Generic;
    
    public partial class wordlearninghistory
    {
        public int id { get; set; }
        public int idwordfrequency { get; set; }
        public Nullable<int> rate { get; set; }
        public int idappuser { get; set; }
        public string pronouncedword { get; set; }
    
        public virtual appuser appuser { get; set; }
        public virtual wordfrequency wordfrequency { get; set; }
    }
}
